### ISSUE TITLE
How can I fetch ADHD200 dataset which is used in your research?

### ISSUE THREAD

**Issue by Maxwell-Wong** [xuesongwang/Contrastive-Functional-Connectivity-Graph-Learning#1]

**Comment by xuesongwang** [comment]
Hi @Maxwell-Wong , 
  You can find the dataset from https://www.nitrc.org/frs/?group_id=383 
  And this paper might help: "The Neuro Bureau ADHD-200 Preprocessed repository"
  https://pubmed.ncbi.nlm.nih.gov/27423255/

Best,
XS

**Comment by Maxwell-Wong** [comment]
Thanks for your reply! But I'm currently encountering another issue. I've downloaded ABIDE_pcp by using `nilearn.dataset ` and downloaded subject_id.txt from https://github.com/sk1712/population-gcn, and now the issue turns to 
`Traceback (most recent call last):
  File "/Users/maxwell/Desktop/Research/CFCG/preprocessing/abide_01-fetch_data.py", line 165, in <module>
    main_multiview()
  File "/Users/maxwell/Desktop/Research/CFCG/preprocessing/abide_01-fetch_data.py", line 141, in main_multiview
    for s, fname in zip(subject_IDs, Reader.fetch_filenames(subject_IDs, files[0], atlas)):
  File "/Users/maxwell/Desktop/Research/CFCG/preprocessing/Reader.py", line 45, in fetch_filenames
    os.chdir(data_folder + '/' + subject_IDs[i])
FileNotFoundError: [Errno 2] No such file or directory: './nilearn_data/ABIDE_pcp/cpac/filt_noglobal/50004'`
And I can't find any  .h5 files from the dataset downloaded by  `nilearn.dataset `.

**Comment by Maxwell-Wong** [comment]
I guess the code here needs to provide a folder for every subject, but I don't know if these folders are downloaded with `nilearn.dataset` or just generated after that.

**Comment by xuesongwang** [comment]
Hello,
You need to change the `root_folder`  and `data_folder` here in `abide_01-fetch_data.py` to your own path

https://github.com/xuesongwang/Contrastive-Functional-Connectivity-Graph-Learning/blob/5f2405a6643229dbf99635edcce983be2f01dc83/preprocessing/abide_01-fetch_data.py#L30-L33

Also need to change the root in `abide_02-process_data.py` as well.

I have modified **BOTH** the readme and   `abide_02-process_data.py`  based on this.  


feel free to let me know how things work :)

**Comment by Maxwell-Wong** [comment]
I've modified this before this is what I modified:
`
code_folder = os.getcwd()
root_folder = './nilearn_data/'
data_folder = os.path.join(root_folder, 'ABIDE_pcp/cpac/filt_noglobal/')
if not os.path.exists(data_folder):
    os.makedirs(data_folder)
`
 but the issue is that `FileNotFoundError: [Errno 2] No such file or directory: './nilearn_data/ABIDE_pcp/cpac/filt_noglobal/50004'`

the related function is below in /preprocessing/Reader.py:
`
def fetch_filenames(subject_IDs, file_type, atlas):
    """
        subject_list : list of short subject IDs in string format
        file_type    : must be one of the available file types
        filemapping  : resulting file name format
    returns:
        filenames    : list of filetypes (same length as subject_list)
    """

    filemapping = {'func_preproc': '_func_preproc.nii.gz',
                   'rois_' + atlas: '_rois_' + atlas + '.1D'}
    # The list to be filled

    filenames = []

    # Fill list with requested file paths
    for i in range(len(subject_IDs)):
        try:
            try:
                os.chdir(data_folder)
                filenames.append(glob.glob('*' + subject_IDs[i] + filemapping[file_type])[0])
            except:
                os.chdir(data_folder + '/' + subject_IDs[i])
                filenames.append(glob.glob('*' + subject_IDs[i] + filemapping[file_type])[0])
        except IndexError:
            filenames.append('N/A')
    return filenames
`
specifically this `os.chdir(data_folder + '/' + subject_IDs[i])`

**Comment by Maxwell-Wong** [comment]
`
code_folder = os.getcwd()
root_folder = './nilearn_data/'
data_folder = os.path.join(root_folder, 'ABIDE_pcp/cpac/filt_noglobal/')
if not os.path.exists(data_folder):
    os.makedirs(data_folder)
`

**Comment by Maxwell-Wong** [comment]
`code_folder = os.getcwd()
root_folder = './nilearn_data/'
data_folder = os.path.join(root_folder, 'ABIDE_pcp/cpac/filt_noglobal/')
if not os.path.exists(data_folder):
    os.makedirs(data_folder)`

**Comment by Maxwell-Wong** [comment]
```
code_folder = os.getcwd()
root_folder = './nilearn_data/'
data_folder = os.path.join(root_folder, 'ABIDE_pcp/cpac/filt_noglobal/')
if not os.path.exists(data_folder):
    os.makedirs(data_folder)
```

**Comment by Maxwell-Wong** [comment]
My dataset in directory `ABIDE_pcp/cpac/filt_noglobal/` contains `Caltech_0051456_rois_cc200.1D`, `KKI_0050793_rois_cc200.1D` and `subject_ID.txt` and so forth, and `Phenotypic_V1_0b_preprocessed1.csv` in  directory ``ABIDE_pcp/cpac` I'm wondering if I have missed some files or not?

**Comment by Maxwell-Wong** [comment]
My dataset in directory ABIDE_pcp/cpac/filt_noglobal/ contains Caltech_0051456_rois_cc200.1D, KKI_0050793_rois_cc200.1D and subject_ID.txt and so forth, and Phenotypic_V1_0b_preprocessed1.csv in directory `ABIDE_pcp/cpac` I'm wondering if I have missed some files or not?

**Comment by Maxwell-Wong** [comment]
Very appreciate it!

**Comment by Maxwell-Wong** [comment]
Appreciate it!

**Comment by Maxwell-Wong** [comment]
I'm encountering another issue.
When I'm executing `abide_02-process_data.py` then it does nothing but displays `Segmentation fault (core dumped)`
I don't know if this is caused by the python package conflict or the code's problem.
Here are all the python packages that I have now:
```
Package                  Version
------------------------ ----------
ase                      3.22.1
certifi                  2022.9.24
charset-normalizer       2.1.1
contourpy                1.0.6
cycler                   0.11.0
deepdish                 0.3.6
fonttools                4.38.0
googledrivedownloader    0.4
h5py                     3.7.0
idna                     3.4
imageio                  2.22.4
importlib-metadata       5.0.0
isodate                  0.6.1
Jinja2                   3.1.2
joblib                   1.2.0
kiwisolver               1.4.4
llvmlite                 0.39.1
lxml                     4.9.1
MarkupSafe               2.1.1
matplotlib               3.6.2
networkx                 2.8.8
nibabel                  4.0.2
nilearn                  0.9.2
numba                    0.56.4
numexpr                  2.8.4
numpy                    1.23.4
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
packaging                21.3
pandas                   1.5.1
Pillow                   9.3.0
pip                      22.2.2
pyparsing                3.0.9
python-dateutil          2.8.2
python-louvain           0.16
pytz                     2022.6
PyWavelets               1.4.1
rdflib                   6.2.0
requests                 2.28.1
scikit-image             0.16.2
scikit-learn             1.1.3
scipy                    1.9.3
seaborn                  0.12.1
setuptools               65.5.0
six                      1.16.0
tables                   3.7.0
threadpoolctl            3.1.0
torch                    1.13.0
torch-geometric          1.7.0
torch-scatter            2.0.9
torch-sparse             0.6.15
torchaudio               0.13.0
torchvision              0.14.0
tqdm                     4.64.1
typing_extensions        4.4.0
urllib3                  1.26.12
wheel                    0.37.1
zipp                     3.10.0
```

**Comment by xuesongwang** [comment]
Can you try to import these packages with command line and identify which package failed?

https://github.com/xuesongwang/Contrastive-Functional-Connectivity-Graph-Learning/blob/3a4cb48c5ed831af1bec504356bce7a7955c8eea/requirements#L1-L14


I suspect it' them:
```
torch-geometric==1.7.0
torch-scatter== 2.0.9
torch-sparse==0.6.15
```

If there are conflicts, you can try to install other versions that match with your environment

**Comment by Maxwell-Wong** [comment]
I found the problem, these three packages conflict with my CUDA and torch version 
torch-geometric      
torch-scatter            
torch-sparse 
I'm repairing it..........

**Comment by Maxwell-Wong** [comment]
There's still an issue that I can't generate multiviewdata_miccai.pt in `abide_02-process_data.py` since it has been killed after 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 871/871 [[17:45<00:00,  1.22s/it]
and it results in empty file `multiviewdata_miccai.pt`

**Comment by xuesongwang** [comment]
If you got an error but got meaningful pt file that's normal,
But if you have an empty file, it sounds like the data are not properly stored.   Could you paste the error message here?

**Comment by Maxwell-Wong** [comment]
Here is all outputs from `abide_02-process_data.py`
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 871/871 [17:45<00:00,  1.22s/it]
Killed
I have no idea why this happened, all .h5 files has been successfully generated and stored in raw_multiview folder

**Comment by Maxwell-Wong** [comment]
If I print the data from `read_multiview_data()`: 
MultiviewData(x1=[200, 200], edge_index1=[2, 39800], y1=[1], edge_attr1=[39800], pos1=[200, 200], x2=[200, 200], edge_index2=[2, 39800], y2=[1], pos2=[200, 200], edge_attr2=[39800], x3=[200, 200], edge_index3=[2, 39800], y3=[1], edge_attr3=[39800], pos3=[200, 200], aux=[7], subject_name=364)
 42%|██████████████████████████████████████████████████████████████                                                                                      | 365/871 [05:08<08:44,  1.04s/it]MultiviewData(x1=[200, 200], edge_index1=[2, 39800], y1=[1], edge_attr1=[39800], pos1=[200, 200], x2=[200, 200], edge_index2=[2, 39800], y2=[1], pos2=[200, 200], edge_attr2=[39800], x3=[200, 200], edge_index3=[2, 39800], y3=[1], edge_attr3=[39800], pos3=[200, 200], aux=[7], subject_name=365)
 42%|███████████████████████████████████████████MultiviewData(x1=[200, 200], edge_index1=[2, 39800], y1=[1], edge_attr1=[39800], pos1=[200, 200], x2=[200, 200], edge_index2=[2, 39800], y2=[1], pos2=[200, 200], edge_attr2=[39800], x3=[200, 200], edge_index3=[2, 39800], y3=[1], edge_attr3=[39800], pos3=[200, 200], aux=[7], subject_name=376)

**Comment by Maxwell-Wong** [comment]
Data might be generated without any wrong. I don't know whether its the problem of `torch.save()`

**Comment by xuesongwang** [comment]
Can you try to save just the data of one subject ?  
Maybe the reason is that the folder "processed" is not created. 
 I will take a look later as well

**Comment by xuesongwang** [comment]
Hi, 
  I think I can confirm that you haven't created the folder yet,  root_folder/raw_multiview and root_folder/processed.  I will add some code to check folder existence soon. Thanks for pointing out :)

**Comment by Maxwell-Wong** [comment]
I have created folder root_dir='./preprocessing/nilearn_data/ABIDE_pcp/cpac/filt_noglobal/processed' and data_dir='./preprocessing/nilearn_data/ABIDE_pcp/cpac/filt_noglobal/raw_multiview'.

**Comment by Maxwell-Wong** [comment]
I've tried only one subject and it can be stored in `multiviewdata_miccai.pt` but cannot store all subjects and displayed the same error "killed".

**Comment by xuesongwang** [comment]
Hi,
  I have double check to save the data again and it works on my side.
![image](https://user-images.githubusercontent.com/19380806/202895010-5c11ff1b-53bd-49d7-b392-4e33fbea3682.png)

I have updated  `abide_02-process_data.py` on the two aspects:
1. check if root_dir exists, otherwise create one. 
2. Add these before importing MultiviewData, just to make sure you can load them from outside the project
```
PROJECT_ROOT = os.path.abspath(os.path.join(
                  os.path.dirname(__file__),
                  os.pardir))
sys.path.append(PROJECT_ROOT)
```
Although I do not think this is relevant to your issues, I suggest deleting data.pt and just to test it for a few epochs:
```
    for subject_id, f in enumerate(tqdm((onlyfiles))):
        if subject_id == 10:
            break
```
hopefully it would work

**Comment by Maxwell-Wong** [comment]
The list `data` is too large? so the OS kills it?

**Comment by xuesongwang** [comment]
If you managed to save it for a few epochs, it might be the reason, but the total list length is 800ish

**Comment by xuesongwang** [comment]
I found this:
https://stackoverflow.com/questions/62560145/pytorch-code-stops-with-message-killed-what-killed-it

**Comment by Maxwell-Wong** [comment]
I've skipped several subjects and it works. Here is another problem.
`train_id, val_id, test_id = train_val_test_split_abide(dataset=dataset, n_sub=len(dataset), drop_sites=None)` in `main_ABIDE.py` results in error:
``
Traceback (most recent call last):
  File "main_ABIDE.py", line 64, in <module>
    train_id, val_id, test_id = train_val_test_split_abide(dataset=dataset, n_sub=len(dataset), drop_sites=None)
  File "/opt/data/private/Huangjy/CFCG/modules/loader.py", line 144, in train_val_test_split_abide
    if site_dict[site] in drop_sites:
TypeError: argument of type 'NoneType' is not iterable
``
It is the problem of `drop_sites=None` ?

**Comment by xuesongwang** [comment]
Yeah I should have left the following line and commented `train_id, val_id, test_id = train_val_test_split_abide(dataset=dataset, n_sub=len(dataset), drop_sites=None)`, which is used for excluding certain sites.

https://github.com/xuesongwang/Contrastive-Functional-Connectivity-Graph-Learning/blob/1a292b6152505380f2a934e9de0768ed2f406124/main_ABIDE.py#L63


I have tested my training and it works fine this time, sorry for inconvenience.  
One last comment, if you want to train and save your own model, you should set
```
parser.add_argument('--load_encoder', type=bool, default=False)
parser.add_argument('--load_clf', type=bool, default=False)
parser.add_argument('--save_model', type=bool, default=True)
```
which would overwrite the saved models `DGC_seed12345.pth` I uploaded in `saved_model` folder


I have updated the main file

**Comment by Maxwell-Wong** [comment]
Thanks a lot!  it can work now!

**Comment by xuesongwang** [comment]
The author has solved the issue
